### ISSUE TITLE
Conda install takes >30 min in clean enviorment

### ISSUE THREAD

**Issue by joshuakirsch** [AstrobioMike/bit#13]
Hi,

I am trying to install this tool and its taking over 30 minutes in a clean conda environment. Any chance you can provide a list of dependencies for a github install instead?

Thanks for making this!
Josh

**Comment by AstrobioMike** [comment]
Hey there, Josh!

Yea conda bogs down quite a bit, mamba should solve it though.

e.g., in the base conda environment install mamba with:

```
conda install -n base -c conda-forge mamba
```

then installing new things, just use mamba as drop-in for conda:

```
mamba create -y -n bit -c conda-forge -c bioconda -c defaults -c astrobiomike bit
```

but still use conda to activate and deactivate:

```
conda activate bit
```

You can see an overview of mamba here if wanted: https://astrobiomike.github.io/unix/conda-intro#bonus-mamba-no-5

**Comment by joshuakirsch** [comment]
Hi,

Thanks for the quick reply. My base enviorment is a dumpster fire, so I installed mamba in the bit enviorment. 
Using the command `mamba install -c astrobiomike bit`, the package still won't install and gives this error:

`Could not solve for environment specs
The following packages are incompatible
└─ bit   is installable with the potential options
   ├─ bit [1.6.11|1.7.06|...|1.8.52] would require
   │  └─ python >=3.7,<3.8.0a0 , which can be installed;
   └─ bit [1.8.53|1.8.54|1.8.55|1.8.56|1.8.57] would require
      └─ python >=3.9,<3.10.0a0 , which can be installed.`

**Comment by joshuakirsch** [comment]
![Screen Shot 2023-05-01 at 3 52 45 PM](https://user-images.githubusercontent.com/69362392/235538084-0558fae1-2ba2-4907-8573-04cf48cdd6d0.png)

**Comment by joshuakirsch** [comment]
Ok figured it out. 
First update python with `mamba install python=3.9` and then
`mamba install -c astrobiomike bit`
Sorry for being a dunce. Thanks again for making this!

**Comment by AstrobioMike** [comment]
Glad you sorted that out, but this still might lead to more problems, as mamba is intended to be installed specifically in the base environment, and then to be used from base to create new environments or install things in base.

And it is absolutely worth doing; mamba is a life-saver when it comes to how slow conda can become. If you literally can’t put it in the base environment currently because of too many conflicts there already, you really should clean out the base environment so that you can (and in the future put most things in their own envs instead of using base). That is only going to become more problematic :/

I know it’s a pain at the time, but it’ll be worth it :)

thanks for writing in about it though! I’m updating the docs too to have this as the recommended install. I didn’t at first because I didn’t want to also explain mamba right there, but just showing it is better than leaving more folks unaware of it
